FROM DOCKER_BASE/dev-lang/golang/1.3.3

MAINTAINER tsaikd "tsaikd@gmail.com"

ENV DOCKER_SRC

ENV SYSD_UI_DIR /opt/go/src/github.com/hacking-thursday/sysd/mods/ui/files

ADD . $DOCKER_SRC

EXPOSE 8080

RUN

CMD

