#!/bin/bash
# set ENV:
# CFKEY=API-key
# CFUSER=username(email)
# CFHOST=host1-you-want-to-change,host2-you-want-to-change
# CFINTERVAL=check-interval-seconds

tmpfile="${tmpfile:-/tmp/cf-ddns-wan-ip.txt}"

function main() {
	if [ "${CFKEY}" ] && [ "${CFUSER}" ] && [ "${CFHOST}" ] ; then
		WAN_IP="$(dig +short myip.opendns.com @resolver1.opendns.com)"
	 
		touch "${tmpfile}"
		if [ "${WAN_IP}" != "$(cat "${tmpfile}")" ] ; then
			printf "%s" "${WAN_IP}" > "${tmpfile}"
			echo "$(date) Update ${CFHOST} to ${WAN_IP}"
			curl -s "https://www.cloudflare.com/api.html?a=DIUP&ip=${WAN_IP}&u=${CFUSER}&tkn=${CFKEY}&hosts=${CFHOST}"
		fi
	fi
}

rm -f "${tmpfile}"

while ((1)) ; do
	main
	sleep "${CFINTERVAL:-300}"
done

