#!/bin/bash
# set ENV:
# CFKEY=API-key
# CFUSER=username(email)
# CFZONE=zone-name
# CFDNIP=x.x.x.x # keep empty for auto detect
# CFHOST=host1-you-want-to-change,host2-you-want-to-change
# CFTYPE=A,CNAME # effect rec type

tmpfile="${tmpfile:-/tmp/cf-ddns-wan-ip.txt}"

function main() {
	if [ "${CFKEY}" ] && [ "${CFUSER}" ] && [ "${CFHOST}" ] ; then
		if [ "${CFDNIP}" ] ; then
			WAN_IP="${CFDNIP}"
		else
			WAN_IP="$(dig +short myip.opendns.com @resolver1.opendns.com)"
		fi
	 
		touch "${tmpfile}"
		if [ "${WAN_IP}" != "$(cat "${tmpfile}")" ] ; then
			printf "%s" "${WAN_IP}" > "${tmpfile}"
			echo "$(date) Update ${CFHOST} to ${WAN_IP}"
			CFDNIP="${WAN_IP}" cf-dns-ip.py
		fi
	fi
}

rm -f "${tmpfile}"

while ((1)) ; do
	main
	sleep "${CFINTERVAL:-300}"
done

